import re
refseq = '/Volumes/Seagate/10022019_ChipSeq/GO_analysis/Abaum_17978-mff_RefSeq_Functional_Annotation.csv'
output = '/Volumes/Seagate/10022019_ChipSeq/GO_analysis/test_GAF.gaf'

outfile = open(output, 'w+')
outfile.write('!gaf-version: 2.1\n')
outfile.write('!\n')
outfile.write('!Generated by GO Central\n')
outfile.write('!\n')
outfile.write('!Date Generated by GOC: 2020-06-01\n')
outfile.write('!\n')
outfile.write('!Header from association file:\n')
outfile.write('!=================================\n')

with open(refseq) as f:
    for line in f:
        line = line.strip().split(',')
        gene = line[1]
        protein = line[2]
        gene_name = line[4]
        product = line[5]
        BP = re.findall(r"\[([A-Za-z0-9:]+)\]", line[25])
        CC = re.findall(r"\[([A-Za-z0-9:]+)\]", line[26])
        MF = re.findall(r"\[([A-Za-z0-9:]+)\]", line[28])
        if len(BP) > 0:
            for term in BP:
                BP_list = ['RefSeq', gene, gene_name, term, protein, 'PMID:', 'Evidence code', 'BP', product, 'synonym', 'type', protein, '20200622', 'EG lab']
                outfile.write('\t'.join(BP_list) + '\n')
        if len(CC) > 0:
            for term in CC:
                CC_list = ['RefSeq', gene, gene_name, term, protein, 'PMID:', 'Evidence code', 'CC', product, 'synonym', 'type', protein, '20200622', 'EG lab']
                outfile.write('\t'.join(CC_list) + '\n')
        if len(MF) > 0:
            for term in MF:
                MF_list = ['RefSeq', gene, gene_name, term, protein, 'PMID:', 'Evidence code', 'MF', product, 'synonym', 'type', protein, '20200622', 'EG lab']
                outfile.write('\t'.join(MF_list) + '\n')

outfile.close()