## Yunfei Dai
## 03/31/2020

"""

This script checks if peaks identified by macs2 are close to transcription start sites (TSS).

Input is .narrowPeak file (generated by macs2)

Output is .bed file containing peaks that are close to at least one TSS.

"""

import pandas as pd

def tss_peak(narrow_peak=/Users/yunfei/macs_test/bam_files/narrowpeak/test7_peaks.narrowPeak, tss, distance=100):
    df_np = pd.read_csv(narrow_peak, sep='\t', names=["ID", "start", "end", "peak", "PAM_pos"])
    df_TSS = pd.read_csv(tss, sep='\t')

print(df_np)